[sdl]
fullresolution = 320x200
windowresolution = 320x200
output = surface
videodriver = dummy

[dosbox]
machine = svga_s3
memsize = 16

[cpu]
core = normal
cputype = pentium
cycles = 3000

[autoexec]
# exit immediately for testing
