[sdl]
fullresolution = 640x480
windowresolution = 640x480
output = surface

[dosbox]
machine = svga_s3
memsize = 16

[cpu]
core = normal
cputype = pentium
cycles = 3000

[render]
scaler = none

[midi]
mpu401 = none

[sblaster]
sbtype = sb16

[autoexec]
mount c /home/yinming/fd2_dat/game
c:
dir *.exe
